version: '3'
services:
  express-app:
    build: .
    container_name: express-container
    ports:
      - "3000:3000"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: hulkgymdb
      NODE_ENV: development
      JWT_SECRET: secretkey
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: hulkgym-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hulkgymdb
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: hulkgym-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin1@gmail.com   
      PGADMIN_DEFAULT_PASSWORD: admin1234      
    ports:
      - "5050:80"
    depends_on:
      - database

volumes:
  db-data: